# Evaluates Tiny Models on Some Datasets
name: Evaluate

on:
  pull_request:
    branches: ["**"] # Run on any branch

jobs:
  generate-and-post:
    if: contains(github.event.pull_request.labels.*.name, 'run-eval')  # Only run if 'run-eval' label is added
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install ".[evaluation]" pandas matplotlib -f https://download.pytorch.org/whl/cpu/torch_stable.html

      - name: Run CI Eval Script
        run: python ci/eval_model.py
      
      - name: Display structure of downloaded files
        run: ls -R

      # - name: Post Image as a Comment
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: ${{ github.repository }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       **Generated Image:**
      #       ![Generated Image](./generated-image/image.png)
